//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace smartRestaurant.ReserveService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReserveServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public partial class ReserveService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTableReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetTableReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReserveCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReserveDinInOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReserveService() {
            this.Url = global::smartRestaurant.Properties.Settings.Default.smartRestaurant_ReserveService_ReserveService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTableReserveCompletedEventHandler GetTableReserveCompleted;
        
        /// <remarks/>
        public event SetTableReserveCompletedEventHandler SetTableReserveCompleted;
        
        /// <remarks/>
        public event SetReserveCancelCompletedEventHandler SetReserveCancelCompleted;
        
        /// <remarks/>
        public event SetReserveDinInCompletedEventHandler SetReserveDinInCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableReserve", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableReserve[] GetTableReserve(System.DateTime date) {
            object[] results = this.Invoke("GetTableReserve", new object[] {
                        date});
            return ((TableReserve[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableReserve(System.DateTime date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableReserve", new object[] {
                        date}, callback, asyncState);
        }
        
        /// <remarks/>
        public TableReserve[] EndGetTableReserve(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableReserve[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTableReserveAsync(System.DateTime date) {
            this.GetTableReserveAsync(date, null);
        }
        
        /// <remarks/>
        public void GetTableReserveAsync(System.DateTime date, object userState) {
            if ((this.GetTableReserveOperationCompleted == null)) {
                this.GetTableReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableReserveOperationCompleted);
            }
            this.InvokeAsync("GetTableReserve", new object[] {
                        date}, this.GetTableReserveOperationCompleted, userState);
        }
        
        private void OnGetTableReserveOperationCompleted(object arg) {
            if ((this.GetTableReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableReserveCompleted(this, new GetTableReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetTableReserve", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetTableReserve(TableReserve reserve, string custFullName) {
            object[] results = this.Invoke("SetTableReserve", new object[] {
                        reserve,
                        custFullName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetTableReserve(TableReserve reserve, string custFullName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetTableReserve", new object[] {
                        reserve,
                        custFullName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSetTableReserve(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetTableReserveAsync(TableReserve reserve, string custFullName) {
            this.SetTableReserveAsync(reserve, custFullName, null);
        }
        
        /// <remarks/>
        public void SetTableReserveAsync(TableReserve reserve, string custFullName, object userState) {
            if ((this.SetTableReserveOperationCompleted == null)) {
                this.SetTableReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetTableReserveOperationCompleted);
            }
            this.InvokeAsync("SetTableReserve", new object[] {
                        reserve,
                        custFullName}, this.SetTableReserveOperationCompleted, userState);
        }
        
        private void OnSetTableReserveOperationCompleted(object arg) {
            if ((this.SetTableReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetTableReserveCompleted(this, new SetTableReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetReserveCancel", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetReserveCancel(string reserveID) {
            object[] results = this.Invoke("SetReserveCancel", new object[] {
                        reserveID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetReserveCancel(string reserveID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetReserveCancel", new object[] {
                        reserveID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetReserveCancel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SetReserveCancelAsync(string reserveID) {
            this.SetReserveCancelAsync(reserveID, null);
        }
        
        /// <remarks/>
        public void SetReserveCancelAsync(string reserveID, object userState) {
            if ((this.SetReserveCancelOperationCompleted == null)) {
                this.SetReserveCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReserveCancelOperationCompleted);
            }
            this.InvokeAsync("SetReserveCancel", new object[] {
                        reserveID}, this.SetReserveCancelOperationCompleted, userState);
        }
        
        private void OnSetReserveCancelOperationCompleted(object arg) {
            if ((this.SetReserveCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReserveCancelCompleted(this, new SetReserveCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetReserveDinIn", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetReserveDinIn(string reserveID, string TableID) {
            object[] results = this.Invoke("SetReserveDinIn", new object[] {
                        reserveID,
                        TableID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetReserveDinIn(string reserveID, string TableID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetReserveDinIn", new object[] {
                        reserveID,
                        TableID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetReserveDinIn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SetReserveDinInAsync(string reserveID, string TableID) {
            this.SetReserveDinInAsync(reserveID, TableID, null);
        }
        
        /// <remarks/>
        public void SetReserveDinInAsync(string reserveID, string TableID, object userState) {
            if ((this.SetReserveDinInOperationCompleted == null)) {
                this.SetReserveDinInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReserveDinInOperationCompleted);
            }
            this.InvokeAsync("SetReserveDinIn", new object[] {
                        reserveID,
                        TableID}, this.SetReserveDinInOperationCompleted, userState);
        }
        
        private void OnSetReserveDinInOperationCompleted(object arg) {
            if ((this.SetReserveDinInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReserveDinInCompleted(this, new SetReserveDinInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class TableReserve {
        
        private string custFirstNameField;
        
        private string custLastNameField;
        
        private string custMiddleNameField;
        
        private int customerIDField;
        
        private System.DateTime reserveDateField;
        
        private int reserveTableIDField;
        
        private int seatField;
        
        private int tableIDField;
        
        /// <remarks/>
        public string custFirstName {
            get {
                return this.custFirstNameField;
            }
            set {
                this.custFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string custLastName {
            get {
                return this.custLastNameField;
            }
            set {
                this.custLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string custMiddleName {
            get {
                return this.custMiddleNameField;
            }
            set {
                this.custMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        public int customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reserveDate {
            get {
                return this.reserveDateField;
            }
            set {
                this.reserveDateField = value;
            }
        }
        
        /// <remarks/>
        public int reserveTableID {
            get {
                return this.reserveTableIDField;
            }
            set {
                this.reserveTableIDField = value;
            }
        }
        
        /// <remarks/>
        public int seat {
            get {
                return this.seatField;
            }
            set {
                this.seatField = value;
            }
        }
        
        /// <remarks/>
        public int tableID {
            get {
                return this.tableIDField;
            }
            set {
                this.tableIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTableReserveCompletedEventHandler(object sender, GetTableReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TableReserve[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TableReserve[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetTableReserveCompletedEventHandler(object sender, SetTableReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetTableReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetTableReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetReserveCancelCompletedEventHandler(object sender, SetReserveCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetReserveCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReserveCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetReserveDinInCompletedEventHandler(object sender, SetReserveDinInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetReserveDinInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReserveDinInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591