//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace smartRestaurant.MenuService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MenuServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public partial class MenuService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMenusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOptionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MenuService() {
            this.Url = global::smartRestaurant.Properties.Settings.Default.smartRestaurant_MenuService_MenuService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMenusCompletedEventHandler GetMenusCompleted;
        
        /// <remarks/>
        public event GetOptionsCompletedEventHandler GetOptionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetMenus", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuType[] GetMenus(string AppName) {
            object[] results = this.Invoke("GetMenus", new object[] {
                        AppName});
            return ((MenuType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMenus(string AppName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMenus", new object[] {
                        AppName}, callback, asyncState);
        }
        
        /// <remarks/>
        public MenuType[] EndGetMenus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MenuType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMenusAsync(string AppName) {
            this.GetMenusAsync(AppName, null);
        }
        
        /// <remarks/>
        public void GetMenusAsync(string AppName, object userState) {
            if ((this.GetMenusOperationCompleted == null)) {
                this.GetMenusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMenusOperationCompleted);
            }
            this.InvokeAsync("GetMenus", new object[] {
                        AppName}, this.GetMenusOperationCompleted, userState);
        }
        
        private void OnGetMenusOperationCompleted(object arg) {
            if ((this.GetMenusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMenusCompleted(this, new GetMenusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetOptions", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuOption[] GetOptions(string AppName) {
            object[] results = this.Invoke("GetOptions", new object[] {
                        AppName});
            return ((MenuOption[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOptions(string AppName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOptions", new object[] {
                        AppName}, callback, asyncState);
        }
        
        /// <remarks/>
        public MenuOption[] EndGetOptions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MenuOption[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOptionsAsync(string AppName) {
            this.GetOptionsAsync(AppName, null);
        }
        
        /// <remarks/>
        public void GetOptionsAsync(string AppName, object userState) {
            if ((this.GetOptionsOperationCompleted == null)) {
                this.GetOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOptionsOperationCompleted);
            }
            this.InvokeAsync("GetOptions", new object[] {
                        AppName}, this.GetOptionsOperationCompleted, userState);
        }
        
        private void OnGetOptionsOperationCompleted(object arg) {
            if ((this.GetOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOptionsCompleted(this, new GetOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class MenuType {
        
        private string descriptionField;
        
        private int idField;
        
        private string nameField;
        
        private double tax1Field;
        
        private double tax2Field;
        
        private MenuItem[] menuItemsField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double Tax1 {
            get {
                return this.tax1Field;
            }
            set {
                this.tax1Field = value;
            }
        }
        
        /// <remarks/>
        public double Tax2 {
            get {
                return this.tax2Field;
            }
            set {
                this.tax2Field = value;
            }
        }
        
        /// <remarks/>
        public MenuItem[] MenuItems {
            get {
                return this.menuItemsField;
            }
            set {
                this.menuItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class MenuItem {
        
        private string descriptionField;
        
        private int idField;
        
        private int keyIDField;
        
        private string keyIDTextField;
        
        private MenuDefault[] menuDefaultsField;
        
        private string nameField;
        
        private double priceField;
        
        private int typeIDField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int KeyID {
            get {
                return this.keyIDField;
            }
            set {
                this.keyIDField = value;
            }
        }
        
        /// <remarks/>
        public string KeyIDText {
            get {
                return this.keyIDTextField;
            }
            set {
                this.keyIDTextField = value;
            }
        }
        
        /// <remarks/>
        public MenuDefault[] MenuDefaults {
            get {
                return this.menuDefaultsField;
            }
            set {
                this.menuDefaultsField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class MenuDefault {
        
        private int menuIDField;
        
        private int optionIDField;
        
        private int defaultChoiceIDField;
        
        /// <remarks/>
        public int MenuID {
            get {
                return this.menuIDField;
            }
            set {
                this.menuIDField = value;
            }
        }
        
        /// <remarks/>
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        public int DefaultChoiceID {
            get {
                return this.defaultChoiceIDField;
            }
            set {
                this.defaultChoiceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class OptionChoice {
        
        private int choiceIDField;
        
        private string choiceNameField;
        
        private int optionIDField;
        
        /// <remarks/>
        public int ChoiceID {
            get {
                return this.choiceIDField;
            }
            set {
                this.choiceIDField = value;
            }
        }
        
        /// <remarks/>
        public string ChoiceName {
            get {
                return this.choiceNameField;
            }
            set {
                this.choiceNameField = value;
            }
        }
        
        /// <remarks/>
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class MenuOption {
        
        private OptionChoice[] optionChoicesField;
        
        private int optionIDField;
        
        private string optionNameField;
        
        /// <remarks/>
        public OptionChoice[] OptionChoices {
            get {
                return this.optionChoicesField;
            }
            set {
                this.optionChoicesField = value;
            }
        }
        
        /// <remarks/>
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        public string OptionName {
            get {
                return this.optionNameField;
            }
            set {
                this.optionNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMenusCompletedEventHandler(object sender, GetMenusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMenusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMenusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MenuType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MenuType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOptionsCompletedEventHandler(object sender, GetOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MenuOption[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MenuOption[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591