//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace smartRestaurant.OrderService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public partial class OrderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderByOrderIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTableReferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetTableReferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOrderPrintOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOrderBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTakeOutListOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintReceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReprintBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCancelReasonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBillDetailWaitingListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServeWaitingOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrderService() {
            this.Url = global::smartRestaurant.Properties.Settings.Default.smartRestaurant_OrderService_OrderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrderCompletedEventHandler GetOrderCompleted;
        
        /// <remarks/>
        public event GetOrderByOrderIDCompletedEventHandler GetOrderByOrderIDCompleted;
        
        /// <remarks/>
        public event GetTableReferenceCompletedEventHandler GetTableReferenceCompleted;
        
        /// <remarks/>
        public event SetTableReferenceCompletedEventHandler SetTableReferenceCompleted;
        
        /// <remarks/>
        public event SendOrderCompletedEventHandler SendOrderCompleted;
        
        /// <remarks/>
        public event SendOrderPrintCompletedEventHandler SendOrderPrintCompleted;
        
        /// <remarks/>
        public event SendOrderBillCompletedEventHandler SendOrderBillCompleted;
        
        /// <remarks/>
        public event GetTakeOutListCompletedEventHandler GetTakeOutListCompleted;
        
        /// <remarks/>
        public event PrintReceiptCompletedEventHandler PrintReceiptCompleted;
        
        /// <remarks/>
        public event PrintBillCompletedEventHandler PrintBillCompleted;
        
        /// <remarks/>
        public event ReprintBillCompletedEventHandler ReprintBillCompleted;
        
        /// <remarks/>
        public event GetCancelReasonCompletedEventHandler GetCancelReasonCompleted;
        
        /// <remarks/>
        public event GetBillDetailWaitingListCompletedEventHandler GetBillDetailWaitingListCompleted;
        
        /// <remarks/>
        public event ServeWaitingOrderCompletedEventHandler ServeWaitingOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetOrder", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInformation GetOrder(int tableID) {
            object[] results = this.Invoke("GetOrder", new object[] {
                        tableID});
            return ((OrderInformation)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrder(int tableID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrder", new object[] {
                        tableID}, callback, asyncState);
        }
        
        /// <remarks/>
        public OrderInformation EndGetOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrderInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderAsync(int tableID) {
            this.GetOrderAsync(tableID, null);
        }
        
        /// <remarks/>
        public void GetOrderAsync(int tableID, object userState) {
            if ((this.GetOrderOperationCompleted == null)) {
                this.GetOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderOperationCompleted);
            }
            this.InvokeAsync("GetOrder", new object[] {
                        tableID}, this.GetOrderOperationCompleted, userState);
        }
        
        private void OnGetOrderOperationCompleted(object arg) {
            if ((this.GetOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderCompleted(this, new GetOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetOrderByOrderID", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInformation GetOrderByOrderID(int OrderID) {
            object[] results = this.Invoke("GetOrderByOrderID", new object[] {
                        OrderID});
            return ((OrderInformation)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrderByOrderID(int OrderID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrderByOrderID", new object[] {
                        OrderID}, callback, asyncState);
        }
        
        /// <remarks/>
        public OrderInformation EndGetOrderByOrderID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrderInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderByOrderIDAsync(int OrderID) {
            this.GetOrderByOrderIDAsync(OrderID, null);
        }
        
        /// <remarks/>
        public void GetOrderByOrderIDAsync(int OrderID, object userState) {
            if ((this.GetOrderByOrderIDOperationCompleted == null)) {
                this.GetOrderByOrderIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderByOrderIDOperationCompleted);
            }
            this.InvokeAsync("GetOrderByOrderID", new object[] {
                        OrderID}, this.GetOrderByOrderIDOperationCompleted, userState);
        }
        
        private void OnGetOrderByOrderIDOperationCompleted(object arg) {
            if ((this.GetOrderByOrderIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderByOrderIDCompleted(this, new GetOrderByOrderIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableReference", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetTableReference(int orderID) {
            object[] results = this.Invoke("GetTableReference", new object[] {
                        orderID});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableReference(int orderID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableReference", new object[] {
                        orderID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int[] EndGetTableReference(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTableReferenceAsync(int orderID) {
            this.GetTableReferenceAsync(orderID, null);
        }
        
        /// <remarks/>
        public void GetTableReferenceAsync(int orderID, object userState) {
            if ((this.GetTableReferenceOperationCompleted == null)) {
                this.GetTableReferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableReferenceOperationCompleted);
            }
            this.InvokeAsync("GetTableReference", new object[] {
                        orderID}, this.GetTableReferenceOperationCompleted, userState);
        }
        
        private void OnGetTableReferenceOperationCompleted(object arg) {
            if ((this.GetTableReferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableReferenceCompleted(this, new GetTableReferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetTableReference", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SetTableReference(int orderID, int[] tableIDList) {
            object[] results = this.Invoke("SetTableReference", new object[] {
                        orderID,
                        tableIDList});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetTableReference(int orderID, int[] tableIDList, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetTableReference", new object[] {
                        orderID,
                        tableIDList}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSetTableReference(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SetTableReferenceAsync(int orderID, int[] tableIDList) {
            this.SetTableReferenceAsync(orderID, tableIDList, null);
        }
        
        /// <remarks/>
        public void SetTableReferenceAsync(int orderID, int[] tableIDList, object userState) {
            if ((this.SetTableReferenceOperationCompleted == null)) {
                this.SetTableReferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetTableReferenceOperationCompleted);
            }
            this.InvokeAsync("SetTableReference", new object[] {
                        orderID,
                        tableIDList}, this.SetTableReferenceOperationCompleted, userState);
        }
        
        private void OnSetTableReferenceOperationCompleted(object arg) {
            if ((this.SetTableReferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetTableReferenceCompleted(this, new SetTableReferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SendOrder", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOrder(OrderInformation orderInfo, int CustID, string CustFullName) {
            object[] results = this.Invoke("SendOrder", new object[] {
                        orderInfo,
                        CustID,
                        CustFullName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendOrder(OrderInformation orderInfo, int CustID, string CustFullName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendOrder", new object[] {
                        orderInfo,
                        CustID,
                        CustFullName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSendOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOrderAsync(OrderInformation orderInfo, int CustID, string CustFullName) {
            this.SendOrderAsync(orderInfo, CustID, CustFullName, null);
        }
        
        /// <remarks/>
        public void SendOrderAsync(OrderInformation orderInfo, int CustID, string CustFullName, object userState) {
            if ((this.SendOrderOperationCompleted == null)) {
                this.SendOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderOperationCompleted);
            }
            this.InvokeAsync("SendOrder", new object[] {
                        orderInfo,
                        CustID,
                        CustFullName}, this.SendOrderOperationCompleted, userState);
        }
        
        private void OnSendOrderOperationCompleted(object arg) {
            if ((this.SendOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderCompleted(this, new SendOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SendOrderPrint", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOrderPrint(OrderInformation orderInfo, int CustID, string CustFullName, bool print) {
            object[] results = this.Invoke("SendOrderPrint", new object[] {
                        orderInfo,
                        CustID,
                        CustFullName,
                        print});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendOrderPrint(OrderInformation orderInfo, int CustID, string CustFullName, bool print, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendOrderPrint", new object[] {
                        orderInfo,
                        CustID,
                        CustFullName,
                        print}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSendOrderPrint(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOrderPrintAsync(OrderInformation orderInfo, int CustID, string CustFullName, bool print) {
            this.SendOrderPrintAsync(orderInfo, CustID, CustFullName, print, null);
        }
        
        /// <remarks/>
        public void SendOrderPrintAsync(OrderInformation orderInfo, int CustID, string CustFullName, bool print, object userState) {
            if ((this.SendOrderPrintOperationCompleted == null)) {
                this.SendOrderPrintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderPrintOperationCompleted);
            }
            this.InvokeAsync("SendOrderPrint", new object[] {
                        orderInfo,
                        CustID,
                        CustFullName,
                        print}, this.SendOrderPrintOperationCompleted, userState);
        }
        
        private void OnSendOrderPrintOperationCompleted(object arg) {
            if ((this.SendOrderPrintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderPrintCompleted(this, new SendOrderPrintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SendOrderBill", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOrderBill(OrderBill Bill) {
            object[] results = this.Invoke("SendOrderBill", new object[] {
                        Bill});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendOrderBill(OrderBill Bill, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendOrderBill", new object[] {
                        Bill}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSendOrderBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOrderBillAsync(OrderBill Bill) {
            this.SendOrderBillAsync(Bill, null);
        }
        
        /// <remarks/>
        public void SendOrderBillAsync(OrderBill Bill, object userState) {
            if ((this.SendOrderBillOperationCompleted == null)) {
                this.SendOrderBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderBillOperationCompleted);
            }
            this.InvokeAsync("SendOrderBill", new object[] {
                        Bill}, this.SendOrderBillOperationCompleted, userState);
        }
        
        private void OnSendOrderBillOperationCompleted(object arg) {
            if ((this.SendOrderBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderBillCompleted(this, new SendOrderBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTakeOutList", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TakeOutInformation[] GetTakeOutList() {
            object[] results = this.Invoke("GetTakeOutList", new object[0]);
            return ((TakeOutInformation[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTakeOutList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTakeOutList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TakeOutInformation[] EndGetTakeOutList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TakeOutInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTakeOutListAsync() {
            this.GetTakeOutListAsync(null);
        }
        
        /// <remarks/>
        public void GetTakeOutListAsync(object userState) {
            if ((this.GetTakeOutListOperationCompleted == null)) {
                this.GetTakeOutListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTakeOutListOperationCompleted);
            }
            this.InvokeAsync("GetTakeOutList", new object[0], this.GetTakeOutListOperationCompleted, userState);
        }
        
        private void OnGetTakeOutListOperationCompleted(object arg) {
            if ((this.GetTakeOutListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTakeOutListCompleted(this, new GetTakeOutListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/PrintReceipt", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PrintReceipt(int OrderBillID) {
            object[] results = this.Invoke("PrintReceipt", new object[] {
                        OrderBillID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintReceipt(int OrderBillID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintReceipt", new object[] {
                        OrderBillID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndPrintReceipt(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PrintReceiptAsync(int OrderBillID) {
            this.PrintReceiptAsync(OrderBillID, null);
        }
        
        /// <remarks/>
        public void PrintReceiptAsync(int OrderBillID, object userState) {
            if ((this.PrintReceiptOperationCompleted == null)) {
                this.PrintReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintReceiptOperationCompleted);
            }
            this.InvokeAsync("PrintReceipt", new object[] {
                        OrderBillID}, this.PrintReceiptOperationCompleted, userState);
        }
        
        private void OnPrintReceiptOperationCompleted(object arg) {
            if ((this.PrintReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintReceiptCompleted(this, new PrintReceiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/PrintBill", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PrintBill(int OrderBillID) {
            object[] results = this.Invoke("PrintBill", new object[] {
                        OrderBillID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintBill(int OrderBillID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintBill", new object[] {
                        OrderBillID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndPrintBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PrintBillAsync(int OrderBillID) {
            this.PrintBillAsync(OrderBillID, null);
        }
        
        /// <remarks/>
        public void PrintBillAsync(int OrderBillID, object userState) {
            if ((this.PrintBillOperationCompleted == null)) {
                this.PrintBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintBillOperationCompleted);
            }
            this.InvokeAsync("PrintBill", new object[] {
                        OrderBillID}, this.PrintBillOperationCompleted, userState);
        }
        
        private void OnPrintBillOperationCompleted(object arg) {
            if ((this.PrintBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintBillCompleted(this, new PrintBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/ReprintBill", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReprintBill(int OrderBillID) {
            object[] results = this.Invoke("ReprintBill", new object[] {
                        OrderBillID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReprintBill(int OrderBillID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReprintBill", new object[] {
                        OrderBillID}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndReprintBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReprintBillAsync(int OrderBillID) {
            this.ReprintBillAsync(OrderBillID, null);
        }
        
        /// <remarks/>
        public void ReprintBillAsync(int OrderBillID, object userState) {
            if ((this.ReprintBillOperationCompleted == null)) {
                this.ReprintBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReprintBillOperationCompleted);
            }
            this.InvokeAsync("ReprintBill", new object[] {
                        OrderBillID}, this.ReprintBillOperationCompleted, userState);
        }
        
        private void OnReprintBillOperationCompleted(object arg) {
            if ((this.ReprintBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReprintBillCompleted(this, new ReprintBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetCancelReason", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CancelReason[] GetCancelReason() {
            object[] results = this.Invoke("GetCancelReason", new object[0]);
            return ((CancelReason[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCancelReason(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCancelReason", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public CancelReason[] EndGetCancelReason(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CancelReason[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCancelReasonAsync() {
            this.GetCancelReasonAsync(null);
        }
        
        /// <remarks/>
        public void GetCancelReasonAsync(object userState) {
            if ((this.GetCancelReasonOperationCompleted == null)) {
                this.GetCancelReasonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCancelReasonOperationCompleted);
            }
            this.InvokeAsync("GetCancelReason", new object[0], this.GetCancelReasonOperationCompleted, userState);
        }
        
        private void OnGetCancelReasonOperationCompleted(object arg) {
            if ((this.GetCancelReasonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCancelReasonCompleted(this, new GetCancelReasonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetBillDetailWaitingList", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderWaiting[] GetBillDetailWaitingList() {
            object[] results = this.Invoke("GetBillDetailWaitingList", new object[0]);
            return ((OrderWaiting[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBillDetailWaitingList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBillDetailWaitingList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public OrderWaiting[] EndGetBillDetailWaitingList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrderWaiting[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBillDetailWaitingListAsync() {
            this.GetBillDetailWaitingListAsync(null);
        }
        
        /// <remarks/>
        public void GetBillDetailWaitingListAsync(object userState) {
            if ((this.GetBillDetailWaitingListOperationCompleted == null)) {
                this.GetBillDetailWaitingListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBillDetailWaitingListOperationCompleted);
            }
            this.InvokeAsync("GetBillDetailWaitingList", new object[0], this.GetBillDetailWaitingListOperationCompleted, userState);
        }
        
        private void OnGetBillDetailWaitingListOperationCompleted(object arg) {
            if ((this.GetBillDetailWaitingListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBillDetailWaitingListCompleted(this, new GetBillDetailWaitingListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/ServeWaitingOrder", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderWaiting[] ServeWaitingOrder(int orderID, int billDetailID) {
            object[] results = this.Invoke("ServeWaitingOrder", new object[] {
                        orderID,
                        billDetailID});
            return ((OrderWaiting[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginServeWaitingOrder(int orderID, int billDetailID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ServeWaitingOrder", new object[] {
                        orderID,
                        billDetailID}, callback, asyncState);
        }
        
        /// <remarks/>
        public OrderWaiting[] EndServeWaitingOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OrderWaiting[])(results[0]));
        }
        
        /// <remarks/>
        public void ServeWaitingOrderAsync(int orderID, int billDetailID) {
            this.ServeWaitingOrderAsync(orderID, billDetailID, null);
        }
        
        /// <remarks/>
        public void ServeWaitingOrderAsync(int orderID, int billDetailID, object userState) {
            if ((this.ServeWaitingOrderOperationCompleted == null)) {
                this.ServeWaitingOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServeWaitingOrderOperationCompleted);
            }
            this.InvokeAsync("ServeWaitingOrder", new object[] {
                        orderID,
                        billDetailID}, this.ServeWaitingOrderOperationCompleted, userState);
        }
        
        private void OnServeWaitingOrderOperationCompleted(object arg) {
            if ((this.ServeWaitingOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServeWaitingOrderCompleted(this, new ServeWaitingOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class OrderInformation {
        
        private OrderBill[] billsField;
        
        private System.DateTime closeOrderDateField;
        
        private System.DateTime createDateField;
        
        private int employeeIDField;
        
        private int numberOfGuestField;
        
        private int orderIDField;
        
        private System.DateTime orderTimeField;
        
        private int tableIDField;
        
        /// <remarks/>
        public OrderBill[] Bills {
            get {
                return this.billsField;
            }
            set {
                this.billsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CloseOrderDate {
            get {
                return this.closeOrderDateField;
            }
            set {
                this.closeOrderDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfGuest {
            get {
                return this.numberOfGuestField;
            }
            set {
                this.numberOfGuestField = value;
            }
        }
        
        /// <remarks/>
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderTime {
            get {
                return this.orderTimeField;
            }
            set {
                this.orderTimeField = value;
            }
        }
        
        /// <remarks/>
        public int TableID {
            get {
                return this.tableIDField;
            }
            set {
                this.tableIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class OrderBill {
        
        private int orderBillIDField;
        
        private int billIDField;
        
        private int employeeIDField;
        
        private System.DateTime closeBillDateField;
        
        private OrderBillItem[] itemsField;
        
        /// <remarks/>
        public int OrderBillID {
            get {
                return this.orderBillIDField;
            }
            set {
                this.orderBillIDField = value;
            }
        }
        
        /// <remarks/>
        public int BillID {
            get {
                return this.billIDField;
            }
            set {
                this.billIDField = value;
            }
        }
        
        /// <remarks/>
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CloseBillDate {
            get {
                return this.closeBillDateField;
            }
            set {
                this.closeBillDateField = value;
            }
        }
        
        /// <remarks/>
        public OrderBillItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class OrderBillItem {
        
        private int billDetailIDField;
        
        private int cancelReasonIDField;
        
        private bool changeFlagField;
        
        private bool defaultOptionField;
        
        private int employeeIDField;
        
        private OrderItemChoice[] itemChoicesField;
        
        private int menuIDField;
        
        private string messageField;
        
        private System.DateTime serveTimeField;
        
        private byte statusField;
        
        private int unitField;
        
        /// <remarks/>
        public int BillDetailID {
            get {
                return this.billDetailIDField;
            }
            set {
                this.billDetailIDField = value;
            }
        }
        
        /// <remarks/>
        public int CancelReasonID {
            get {
                return this.cancelReasonIDField;
            }
            set {
                this.cancelReasonIDField = value;
            }
        }
        
        /// <remarks/>
        public bool ChangeFlag {
            get {
                return this.changeFlagField;
            }
            set {
                this.changeFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultOption {
            get {
                return this.defaultOptionField;
            }
            set {
                this.defaultOptionField = value;
            }
        }
        
        /// <remarks/>
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        public OrderItemChoice[] ItemChoices {
            get {
                return this.itemChoicesField;
            }
            set {
                this.itemChoicesField = value;
            }
        }
        
        /// <remarks/>
        public int MenuID {
            get {
                return this.menuIDField;
            }
            set {
                this.menuIDField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ServeTime {
            get {
                return this.serveTimeField;
            }
            set {
                this.serveTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class OrderItemChoice {
        
        private int optionIDField;
        
        private int choiceIDField;
        
        /// <remarks/>
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        public int ChoiceID {
            get {
                return this.choiceIDField;
            }
            set {
                this.choiceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class OrderBillItemWaiting {
        
        private int billDetailIDField;
        
        private string choiceField;
        
        private string menuKeyIDField;
        
        private int unitField;
        
        /// <remarks/>
        public int BillDetailID {
            get {
                return this.billDetailIDField;
            }
            set {
                this.billDetailIDField = value;
            }
        }
        
        /// <remarks/>
        public string Choice {
            get {
                return this.choiceField;
            }
            set {
                this.choiceField = value;
            }
        }
        
        /// <remarks/>
        public string MenuKeyID {
            get {
                return this.menuKeyIDField;
            }
            set {
                this.menuKeyIDField = value;
            }
        }
        
        /// <remarks/>
        public int Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class OrderWaiting {
        
        private OrderBillItemWaiting[] itemsField;
        
        private int orderIDField;
        
        private string tableNameField;
        
        /// <remarks/>
        public OrderBillItemWaiting[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class CancelReason {
        
        private int cancelReasonIDField;
        
        private string reasonField;
        
        /// <remarks/>
        public int CancelReasonID {
            get {
                return this.cancelReasonIDField;
            }
            set {
                this.cancelReasonIDField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class CustomerInformation {
        
        private string addressField;
        
        private int custIDField;
        
        private string descriptionField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string otherRoadNameField;
        
        private int roadIDField;
        
        private string telephoneField;
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public int CustID {
            get {
                return this.custIDField;
            }
            set {
                this.custIDField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string OtherRoadName {
            get {
                return this.otherRoadNameField;
            }
            set {
                this.otherRoadNameField = value;
            }
        }
        
        /// <remarks/>
        public int RoadID {
            get {
                return this.roadIDField;
            }
            set {
                this.roadIDField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class TakeOutInformation {
        
        private CustomerInformation custInfoField;
        
        private System.DateTime orderDateField;
        
        private int orderIDField;
        
        /// <remarks/>
        public CustomerInformation CustInfo {
            get {
                return this.custInfoField;
            }
            set {
                this.custInfoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderCompletedEventHandler(object sender, GetOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderByOrderIDCompletedEventHandler(object sender, GetOrderByOrderIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderByOrderIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderByOrderIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTableReferenceCompletedEventHandler(object sender, GetTableReferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableReferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableReferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetTableReferenceCompletedEventHandler(object sender, SetTableReferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetTableReferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetTableReferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendOrderCompletedEventHandler(object sender, SendOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendOrderPrintCompletedEventHandler(object sender, SendOrderPrintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderPrintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrderPrintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendOrderBillCompletedEventHandler(object sender, SendOrderBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrderBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTakeOutListCompletedEventHandler(object sender, GetTakeOutListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTakeOutListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTakeOutListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TakeOutInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TakeOutInformation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PrintReceiptCompletedEventHandler(object sender, PrintReceiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintReceiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintReceiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PrintBillCompletedEventHandler(object sender, PrintBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReprintBillCompletedEventHandler(object sender, ReprintBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReprintBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReprintBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCancelReasonCompletedEventHandler(object sender, GetCancelReasonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCancelReasonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCancelReasonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelReason[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelReason[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBillDetailWaitingListCompletedEventHandler(object sender, GetBillDetailWaitingListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBillDetailWaitingListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBillDetailWaitingListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderWaiting[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderWaiting[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ServeWaitingOrderCompletedEventHandler(object sender, ServeWaitingOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServeWaitingOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServeWaitingOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderWaiting[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderWaiting[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591