//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace smartRestaurant.CustomerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public partial class CustomerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoadsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetCustomerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerService() {
            this.Url = global::smartRestaurant.Properties.Settings.Default.smartRestaurant_CustomerService_CustomerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteCustomerCompletedEventHandler DeleteCustomerCompleted;
        
        /// <remarks/>
        public event GetCustomersCompletedEventHandler GetCustomersCompleted;
        
        /// <remarks/>
        public event GetRoadsCompletedEventHandler GetRoadsCompleted;
        
        /// <remarks/>
        public event SearchCustomersCompletedEventHandler SearchCustomersCompleted;
        
        /// <remarks/>
        public event SetCustomerCompletedEventHandler SetCustomerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/DeleteCustomer", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteCustomer(int custID) {
            object[] results = this.Invoke("DeleteCustomer", new object[] {
                        custID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteCustomer(int custID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteCustomer", new object[] {
                        custID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDeleteCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCustomerAsync(int custID) {
            this.DeleteCustomerAsync(custID, null);
        }
        
        /// <remarks/>
        public void DeleteCustomerAsync(int custID, object userState) {
            if ((this.DeleteCustomerOperationCompleted == null)) {
                this.DeleteCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCustomerOperationCompleted);
            }
            this.InvokeAsync("DeleteCustomer", new object[] {
                        custID}, this.DeleteCustomerOperationCompleted, userState);
        }
        
        private void OnDeleteCustomerOperationCompleted(object arg) {
            if ((this.DeleteCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCustomerCompleted(this, new DeleteCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetCustomers", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerInformation[] GetCustomers() {
            object[] results = this.Invoke("GetCustomers", new object[0]);
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerInformation[] EndGetCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomersAsync() {
            this.GetCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomersAsync(object userState) {
            if ((this.GetCustomersOperationCompleted == null)) {
                this.GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersOperationCompleted);
            }
            this.InvokeAsync("GetCustomers", new object[0], this.GetCustomersOperationCompleted, userState);
        }
        
        private void OnGetCustomersOperationCompleted(object arg) {
            if ((this.GetCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetRoads", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Road[] GetRoads() {
            object[] results = this.Invoke("GetRoads", new object[0]);
            return ((Road[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRoads(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRoads", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Road[] EndGetRoads(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Road[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRoadsAsync() {
            this.GetRoadsAsync(null);
        }
        
        /// <remarks/>
        public void GetRoadsAsync(object userState) {
            if ((this.GetRoadsOperationCompleted == null)) {
                this.GetRoadsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoadsOperationCompleted);
            }
            this.InvokeAsync("GetRoads", new object[0], this.GetRoadsOperationCompleted, userState);
        }
        
        private void OnGetRoadsOperationCompleted(object arg) {
            if ((this.GetRoadsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoadsCompleted(this, new GetRoadsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SearchCustomers", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerInformation[] SearchCustomers(string telephone, string fname, string mname, string lname) {
            object[] results = this.Invoke("SearchCustomers", new object[] {
                        telephone,
                        fname,
                        mname,
                        lname});
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchCustomers(string telephone, string fname, string mname, string lname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchCustomers", new object[] {
                        telephone,
                        fname,
                        mname,
                        lname}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerInformation[] EndSearchCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchCustomersAsync(string telephone, string fname, string mname, string lname) {
            this.SearchCustomersAsync(telephone, fname, mname, lname, null);
        }
        
        /// <remarks/>
        public void SearchCustomersAsync(string telephone, string fname, string mname, string lname, object userState) {
            if ((this.SearchCustomersOperationCompleted == null)) {
                this.SearchCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchCustomersOperationCompleted);
            }
            this.InvokeAsync("SearchCustomers", new object[] {
                        telephone,
                        fname,
                        mname,
                        lname}, this.SearchCustomersOperationCompleted, userState);
        }
        
        private void OnSearchCustomersOperationCompleted(object arg) {
            if ((this.SearchCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCustomersCompleted(this, new SearchCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SetCustomer", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetCustomer(CustomerInformation custInfo) {
            object[] results = this.Invoke("SetCustomer", new object[] {
                        custInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetCustomer(CustomerInformation custInfo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetCustomer", new object[] {
                        custInfo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSetCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetCustomerAsync(CustomerInformation custInfo) {
            this.SetCustomerAsync(custInfo, null);
        }
        
        /// <remarks/>
        public void SetCustomerAsync(CustomerInformation custInfo, object userState) {
            if ((this.SetCustomerOperationCompleted == null)) {
                this.SetCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCustomerOperationCompleted);
            }
            this.InvokeAsync("SetCustomer", new object[] {
                        custInfo}, this.SetCustomerOperationCompleted, userState);
        }
        
        private void OnSetCustomerOperationCompleted(object arg) {
            if ((this.SetCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCustomerCompleted(this, new SetCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class CustomerInformation {
        
        private string addressField;
        
        private int custIDField;
        
        private string descriptionField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string otherRoadNameField;
        
        private int roadIDField;
        
        private string telephoneField;
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public int CustID {
            get {
                return this.custIDField;
            }
            set {
                this.custIDField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string OtherRoadName {
            get {
                return this.otherRoadNameField;
            }
            set {
                this.otherRoadNameField = value;
            }
        }
        
        /// <remarks/>
        public int RoadID {
            get {
                return this.roadIDField;
            }
            set {
                this.roadIDField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class Road {
        
        private string areaNameField;
        
        private string areaTypeNameField;
        
        private int roadIDField;
        
        private string roadNameField;
        
        private string roadTypeNameField;
        
        /// <remarks/>
        public string AreaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
            }
        }
        
        /// <remarks/>
        public string AreaTypeName {
            get {
                return this.areaTypeNameField;
            }
            set {
                this.areaTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public int RoadID {
            get {
                return this.roadIDField;
            }
            set {
                this.roadIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoadName {
            get {
                return this.roadNameField;
            }
            set {
                this.roadNameField = value;
            }
        }
        
        /// <remarks/>
        public string RoadTypeName {
            get {
                return this.roadTypeNameField;
            }
            set {
                this.roadTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteCustomerCompletedEventHandler(object sender, DeleteCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomersCompletedEventHandler(object sender, GetCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerInformation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRoadsCompletedEventHandler(object sender, GetRoadsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoadsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoadsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Road[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Road[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchCustomersCompletedEventHandler(object sender, SearchCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerInformation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetCustomerCompletedEventHandler(object sender, SetCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591