//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace smartRestaurant.TableService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TableServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public partial class TableService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTableListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTableInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTableStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTableLockInuseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TableService() {
            this.Url = global::smartRestaurant.Properties.Settings.Default.smartRestaurant_TableService_TableService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTableListCompletedEventHandler GetTableListCompleted;
        
        /// <remarks/>
        public event GetTableInformationCompletedEventHandler GetTableInformationCompleted;
        
        /// <remarks/>
        public event GetTableStatusCompletedEventHandler GetTableStatusCompleted;
        
        /// <remarks/>
        public event UpdateTableLockInuseCompletedEventHandler UpdateTableLockInuseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableList", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableInformation[] GetTableList() {
            object[] results = this.Invoke("GetTableList", new object[0]);
            return ((TableInformation[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TableInformation[] EndGetTableList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableInformation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTableListAsync() {
            this.GetTableListAsync(null);
        }
        
        /// <remarks/>
        public void GetTableListAsync(object userState) {
            if ((this.GetTableListOperationCompleted == null)) {
                this.GetTableListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableListOperationCompleted);
            }
            this.InvokeAsync("GetTableList", new object[0], this.GetTableListOperationCompleted, userState);
        }
        
        private void OnGetTableListOperationCompleted(object arg) {
            if ((this.GetTableListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableListCompleted(this, new GetTableListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableInformation", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableInformation GetTableInformation(int tableID) {
            object[] results = this.Invoke("GetTableInformation", new object[] {
                        tableID});
            return ((TableInformation)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableInformation(int tableID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableInformation", new object[] {
                        tableID}, callback, asyncState);
        }
        
        /// <remarks/>
        public TableInformation EndGetTableInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetTableInformationAsync(int tableID) {
            this.GetTableInformationAsync(tableID, null);
        }
        
        /// <remarks/>
        public void GetTableInformationAsync(int tableID, object userState) {
            if ((this.GetTableInformationOperationCompleted == null)) {
                this.GetTableInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableInformationOperationCompleted);
            }
            this.InvokeAsync("GetTableInformation", new object[] {
                        tableID}, this.GetTableInformationOperationCompleted, userState);
        }
        
        private void OnGetTableInformationOperationCompleted(object arg) {
            if ((this.GetTableInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableInformationCompleted(this, new GetTableInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTableStatus", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TableStatus[] GetTableStatus() {
            object[] results = this.Invoke("GetTableStatus", new object[0]);
            return ((TableStatus[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableStatus(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableStatus", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TableStatus[] EndGetTableStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TableStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTableStatusAsync() {
            this.GetTableStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetTableStatusAsync(object userState) {
            if ((this.GetTableStatusOperationCompleted == null)) {
                this.GetTableStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTableStatusOperationCompleted);
            }
            this.InvokeAsync("GetTableStatus", new object[0], this.GetTableStatusOperationCompleted, userState);
        }
        
        private void OnGetTableStatusOperationCompleted(object arg) {
            if ((this.GetTableStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTableStatusCompleted(this, new GetTableStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/UpdateTableLockInuse", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateTableLockInuse(int tableID, bool lockInUse) {
            object[] results = this.Invoke("UpdateTableLockInuse", new object[] {
                        tableID,
                        lockInUse});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateTableLockInuse(int tableID, bool lockInUse, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateTableLockInuse", new object[] {
                        tableID,
                        lockInUse}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUpdateTableLockInuse(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTableLockInuseAsync(int tableID, bool lockInUse) {
            this.UpdateTableLockInuseAsync(tableID, lockInUse, null);
        }
        
        /// <remarks/>
        public void UpdateTableLockInuseAsync(int tableID, bool lockInUse, object userState) {
            if ((this.UpdateTableLockInuseOperationCompleted == null)) {
                this.UpdateTableLockInuseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTableLockInuseOperationCompleted);
            }
            this.InvokeAsync("UpdateTableLockInuse", new object[] {
                        tableID,
                        lockInUse}, this.UpdateTableLockInuseOperationCompleted, userState);
        }
        
        private void OnUpdateTableLockInuseOperationCompleted(object arg) {
            if ((this.UpdateTableLockInuseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTableLockInuseCompleted(this, new UpdateTableLockInuseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class TableInformation {
        
        private int tableIDField;
        
        private int numberOfSeatField;
        
        private string tableNameField;
        
        /// <remarks/>
        public int TableID {
            get {
                return this.tableIDField;
            }
            set {
                this.tableIDField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfSeat {
            get {
                return this.numberOfSeatField;
            }
            set {
                this.numberOfSeatField = value;
            }
        }
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class TableStatus {
        
        private bool inUseField;
        
        private bool isPrintBillField;
        
        private bool isWaitingItemField;
        
        private bool lockInUseField;
        
        private int tableIDField;
        
        private string tableNameField;
        
        /// <remarks/>
        public bool InUse {
            get {
                return this.inUseField;
            }
            set {
                this.inUseField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPrintBill {
            get {
                return this.isPrintBillField;
            }
            set {
                this.isPrintBillField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWaitingItem {
            get {
                return this.isWaitingItemField;
            }
            set {
                this.isWaitingItemField = value;
            }
        }
        
        /// <remarks/>
        public bool LockInUse {
            get {
                return this.lockInUseField;
            }
            set {
                this.lockInUseField = value;
            }
        }
        
        /// <remarks/>
        public int TableID {
            get {
                return this.tableIDField;
            }
            set {
                this.tableIDField = value;
            }
        }
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTableListCompletedEventHandler(object sender, GetTableListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TableInformation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TableInformation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTableInformationCompletedEventHandler(object sender, GetTableInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TableInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TableInformation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTableStatusCompletedEventHandler(object sender, GetTableStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTableStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTableStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TableStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TableStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateTableLockInuseCompletedEventHandler(object sender, UpdateTableLockInuseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTableLockInuseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTableLockInuseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591