//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace smartRestaurant.CheckBillService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CheckBillServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public partial class CheckBillService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetComputeBillPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTodayTipOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDescriptionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CheckBillService() {
            this.Url = global::smartRestaurant.Properties.Settings.Default.smartRestaurant_CheckBillService_CheckBillService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetInvoiceCompletedEventHandler GetInvoiceCompleted;
        
        /// <remarks/>
        public event GetInvoiceByIDCompletedEventHandler GetInvoiceByIDCompleted;
        
        /// <remarks/>
        public event SendInvoiceCompletedEventHandler SendInvoiceCompleted;
        
        /// <remarks/>
        public event GetComputeBillPriceCompletedEventHandler GetComputeBillPriceCompleted;
        
        /// <remarks/>
        public event GetTodayTipCompletedEventHandler GetTodayTipCompleted;
        
        /// <remarks/>
        public event GetDescriptionCompletedEventHandler GetDescriptionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetInvoice", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Invoice GetInvoice(int orderBillID) {
            object[] results = this.Invoke("GetInvoice", new object[] {
                        orderBillID});
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInvoice(int orderBillID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInvoice", new object[] {
                        orderBillID}, callback, asyncState);
        }
        
        /// <remarks/>
        public Invoice EndGetInvoice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceAsync(int orderBillID) {
            this.GetInvoiceAsync(orderBillID, null);
        }
        
        /// <remarks/>
        public void GetInvoiceAsync(int orderBillID, object userState) {
            if ((this.GetInvoiceOperationCompleted == null)) {
                this.GetInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceOperationCompleted);
            }
            this.InvokeAsync("GetInvoice", new object[] {
                        orderBillID}, this.GetInvoiceOperationCompleted, userState);
        }
        
        private void OnGetInvoiceOperationCompleted(object arg) {
            if ((this.GetInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceCompleted(this, new GetInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetInvoiceByID", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Invoice GetInvoiceByID(int invoiceID) {
            object[] results = this.Invoke("GetInvoiceByID", new object[] {
                        invoiceID});
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInvoiceByID(int invoiceID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInvoiceByID", new object[] {
                        invoiceID}, callback, asyncState);
        }
        
        /// <remarks/>
        public Invoice EndGetInvoiceByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Invoice)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceByIDAsync(int invoiceID) {
            this.GetInvoiceByIDAsync(invoiceID, null);
        }
        
        /// <remarks/>
        public void GetInvoiceByIDAsync(int invoiceID, object userState) {
            if ((this.GetInvoiceByIDOperationCompleted == null)) {
                this.GetInvoiceByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceByIDOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceByID", new object[] {
                        invoiceID}, this.GetInvoiceByIDOperationCompleted, userState);
        }
        
        private void OnGetInvoiceByIDOperationCompleted(object arg) {
            if ((this.GetInvoiceByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceByIDCompleted(this, new GetInvoiceByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/SendInvoice", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendInvoice(Invoice invoice) {
            object[] results = this.Invoke("SendInvoice", new object[] {
                        invoice});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendInvoice(Invoice invoice, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendInvoice", new object[] {
                        invoice}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSendInvoice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendInvoiceAsync(Invoice invoice) {
            this.SendInvoiceAsync(invoice, null);
        }
        
        /// <remarks/>
        public void SendInvoiceAsync(Invoice invoice, object userState) {
            if ((this.SendInvoiceOperationCompleted == null)) {
                this.SendInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendInvoiceOperationCompleted);
            }
            this.InvokeAsync("SendInvoice", new object[] {
                        invoice}, this.SendInvoiceOperationCompleted, userState);
        }
        
        private void OnSendInvoiceOperationCompleted(object arg) {
            if ((this.SendInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendInvoiceCompleted(this, new SendInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetComputeBillPrice", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillPrice GetComputeBillPrice(int orderBillID) {
            object[] results = this.Invoke("GetComputeBillPrice", new object[] {
                        orderBillID});
            return ((BillPrice)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetComputeBillPrice(int orderBillID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetComputeBillPrice", new object[] {
                        orderBillID}, callback, asyncState);
        }
        
        /// <remarks/>
        public BillPrice EndGetComputeBillPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillPrice)(results[0]));
        }
        
        /// <remarks/>
        public void GetComputeBillPriceAsync(int orderBillID) {
            this.GetComputeBillPriceAsync(orderBillID, null);
        }
        
        /// <remarks/>
        public void GetComputeBillPriceAsync(int orderBillID, object userState) {
            if ((this.GetComputeBillPriceOperationCompleted == null)) {
                this.GetComputeBillPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetComputeBillPriceOperationCompleted);
            }
            this.InvokeAsync("GetComputeBillPrice", new object[] {
                        orderBillID}, this.GetComputeBillPriceOperationCompleted, userState);
        }
        
        private void OnGetComputeBillPriceOperationCompleted(object arg) {
            if ((this.GetComputeBillPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetComputeBillPriceCompleted(this, new GetComputeBillPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetTodayTip", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetTodayTip() {
            object[] results = this.Invoke("GetTodayTip", new object[0]);
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTodayTip(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTodayTip", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public double EndGetTodayTip(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void GetTodayTipAsync() {
            this.GetTodayTipAsync(null);
        }
        
        /// <remarks/>
        public void GetTodayTipAsync(object userState) {
            if ((this.GetTodayTipOperationCompleted == null)) {
                this.GetTodayTipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodayTipOperationCompleted);
            }
            this.InvokeAsync("GetTodayTip", new object[0], this.GetTodayTipOperationCompleted, userState);
        }
        
        private void OnGetTodayTipOperationCompleted(object arg) {
            if ((this.GetTodayTipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodayTipCompleted(this, new GetTodayTipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetDescription", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDescription(string id) {
            object[] results = this.Invoke("GetDescription", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDescription(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDescription", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetDescription(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDescriptionAsync(string id) {
            this.GetDescriptionAsync(id, null);
        }
        
        /// <remarks/>
        public void GetDescriptionAsync(string id, object userState) {
            if ((this.GetDescriptionOperationCompleted == null)) {
                this.GetDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDescriptionOperationCompleted);
            }
            this.InvokeAsync("GetDescription", new object[] {
                        id}, this.GetDescriptionOperationCompleted, userState);
        }
        
        private void OnGetDescriptionOperationCompleted(object arg) {
            if ((this.GetDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDescriptionCompleted(this, new GetDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class Invoice {
        
        private InvoiceDiscount[] discountsField;
        
        private int employeeIDField;
        
        private int invoiceIDField;
        
        private string invoiceNoteField;
        
        private int orderBillIDField;
        
        private int paymentMethodIDField;
        
        private InvoicePayment[] paymentsField;
        
        private int pointField;
        
        private int refInvoiceField;
        
        private double tax1Field;
        
        private double tax2Field;
        
        private double totalDiscountField;
        
        private double totalPriceField;
        
        private double totalReceiveField;
        
        /// <remarks/>
        public InvoiceDiscount[] discounts {
            get {
                return this.discountsField;
            }
            set {
                this.discountsField = value;
            }
        }
        
        /// <remarks/>
        public int employeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        public int invoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
            }
        }
        
        /// <remarks/>
        public string invoiceNote {
            get {
                return this.invoiceNoteField;
            }
            set {
                this.invoiceNoteField = value;
            }
        }
        
        /// <remarks/>
        public int orderBillID {
            get {
                return this.orderBillIDField;
            }
            set {
                this.orderBillIDField = value;
            }
        }
        
        /// <remarks/>
        public int paymentMethodID {
            get {
                return this.paymentMethodIDField;
            }
            set {
                this.paymentMethodIDField = value;
            }
        }
        
        /// <remarks/>
        public InvoicePayment[] payments {
            get {
                return this.paymentsField;
            }
            set {
                this.paymentsField = value;
            }
        }
        
        /// <remarks/>
        public int point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public int refInvoice {
            get {
                return this.refInvoiceField;
            }
            set {
                this.refInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public double tax1 {
            get {
                return this.tax1Field;
            }
            set {
                this.tax1Field = value;
            }
        }
        
        /// <remarks/>
        public double tax2 {
            get {
                return this.tax2Field;
            }
            set {
                this.tax2Field = value;
            }
        }
        
        /// <remarks/>
        public double totalDiscount {
            get {
                return this.totalDiscountField;
            }
            set {
                this.totalDiscountField = value;
            }
        }
        
        /// <remarks/>
        public double totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        public double totalReceive {
            get {
                return this.totalReceiveField;
            }
            set {
                this.totalReceiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class InvoiceDiscount {
        
        private int invoiceDiscountIDField;
        
        private int invoiceIDField;
        
        private int promotionIDField;
        
        /// <remarks/>
        public int invoiceDiscountID {
            get {
                return this.invoiceDiscountIDField;
            }
            set {
                this.invoiceDiscountIDField = value;
            }
        }
        
        /// <remarks/>
        public int invoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
            }
        }
        
        /// <remarks/>
        public int promotionID {
            get {
                return this.promotionIDField;
            }
            set {
                this.promotionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class BillPrice {
        
        private double totalPriceField;
        
        private double totalDiscountField;
        
        private double totalTax1Field;
        
        private double totalTax2Field;
        
        /// <remarks/>
        public double totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        public double totalDiscount {
            get {
                return this.totalDiscountField;
            }
            set {
                this.totalDiscountField = value;
            }
        }
        
        /// <remarks/>
        public double totalTax1 {
            get {
                return this.totalTax1Field;
            }
            set {
                this.totalTax1Field = value;
            }
        }
        
        /// <remarks/>
        public double totalTax2 {
            get {
                return this.totalTax2Field;
            }
            set {
                this.totalTax2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class InvoicePayment {
        
        private int paymentMethodIDField;
        
        private double receiveField;
        
        /// <remarks/>
        public int paymentMethodID {
            get {
                return this.paymentMethodIDField;
            }
            set {
                this.paymentMethodIDField = value;
            }
        }
        
        /// <remarks/>
        public double receive {
            get {
                return this.receiveField;
            }
            set {
                this.receiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetInvoiceCompletedEventHandler(object sender, GetInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Invoice Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Invoice)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetInvoiceByIDCompletedEventHandler(object sender, GetInvoiceByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Invoice Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Invoice)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendInvoiceCompletedEventHandler(object sender, SendInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetComputeBillPriceCompletedEventHandler(object sender, GetComputeBillPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetComputeBillPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetComputeBillPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillPrice Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillPrice)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTodayTipCompletedEventHandler(object sender, GetTodayTipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodayTipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodayTipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDescriptionCompletedEventHandler(object sender, GetDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591