//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace smartRestaurant.PaymentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaymentServiceSoap", Namespace="http://ws.smartRestaurant.net")]
    public partial class PaymentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPaymentMethodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCouponsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGiftVouchersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDiscountsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PaymentService() {
            this.Url = global::smartRestaurant.Properties.Settings.Default.smartRestaurant_PaymentService_PaymentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPaymentMethodsCompletedEventHandler GetPaymentMethodsCompleted;
        
        /// <remarks/>
        public event GetCouponsCompletedEventHandler GetCouponsCompleted;
        
        /// <remarks/>
        public event GetGiftVouchersCompletedEventHandler GetGiftVouchersCompleted;
        
        /// <remarks/>
        public event GetDiscountsCompletedEventHandler GetDiscountsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetPaymentMethods", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentMethod[] GetPaymentMethods() {
            object[] results = this.Invoke("GetPaymentMethods", new object[0]);
            return ((PaymentMethod[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPaymentMethods(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPaymentMethods", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public PaymentMethod[] EndGetPaymentMethods(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PaymentMethod[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentMethodsAsync() {
            this.GetPaymentMethodsAsync(null);
        }
        
        /// <remarks/>
        public void GetPaymentMethodsAsync(object userState) {
            if ((this.GetPaymentMethodsOperationCompleted == null)) {
                this.GetPaymentMethodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentMethodsOperationCompleted);
            }
            this.InvokeAsync("GetPaymentMethods", new object[0], this.GetPaymentMethodsOperationCompleted, userState);
        }
        
        private void OnGetPaymentMethodsOperationCompleted(object arg) {
            if ((this.GetPaymentMethodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentMethodsCompleted(this, new GetPaymentMethodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetCoupons", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PromotionCard[] GetCoupons() {
            object[] results = this.Invoke("GetCoupons", new object[0]);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCoupons(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCoupons", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public PromotionCard[] EndGetCoupons(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCouponsAsync() {
            this.GetCouponsAsync(null);
        }
        
        /// <remarks/>
        public void GetCouponsAsync(object userState) {
            if ((this.GetCouponsOperationCompleted == null)) {
                this.GetCouponsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCouponsOperationCompleted);
            }
            this.InvokeAsync("GetCoupons", new object[0], this.GetCouponsOperationCompleted, userState);
        }
        
        private void OnGetCouponsOperationCompleted(object arg) {
            if ((this.GetCouponsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCouponsCompleted(this, new GetCouponsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetGiftVouchers", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PromotionCard[] GetGiftVouchers() {
            object[] results = this.Invoke("GetGiftVouchers", new object[0]);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGiftVouchers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGiftVouchers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public PromotionCard[] EndGetGiftVouchers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PromotionCard[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGiftVouchersAsync() {
            this.GetGiftVouchersAsync(null);
        }
        
        /// <remarks/>
        public void GetGiftVouchersAsync(object userState) {
            if ((this.GetGiftVouchersOperationCompleted == null)) {
                this.GetGiftVouchersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGiftVouchersOperationCompleted);
            }
            this.InvokeAsync("GetGiftVouchers", new object[0], this.GetGiftVouchersOperationCompleted, userState);
        }
        
        private void OnGetGiftVouchersOperationCompleted(object arg) {
            if ((this.GetGiftVouchersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGiftVouchersCompleted(this, new GetGiftVouchersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.smartRestaurant.net/GetDiscounts", RequestNamespace="http://ws.smartRestaurant.net", ResponseNamespace="http://ws.smartRestaurant.net", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Discount[] GetDiscounts() {
            object[] results = this.Invoke("GetDiscounts", new object[0]);
            return ((Discount[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDiscounts(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDiscounts", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Discount[] EndGetDiscounts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Discount[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDiscountsAsync() {
            this.GetDiscountsAsync(null);
        }
        
        /// <remarks/>
        public void GetDiscountsAsync(object userState) {
            if ((this.GetDiscountsOperationCompleted == null)) {
                this.GetDiscountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDiscountsOperationCompleted);
            }
            this.InvokeAsync("GetDiscounts", new object[0], this.GetDiscountsOperationCompleted, userState);
        }
        
        private void OnGetDiscountsOperationCompleted(object arg) {
            if ((this.GetDiscountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDiscountsCompleted(this, new GetDiscountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class PaymentMethod {
        
        private int paymentMethodIDField;
        
        private string paymentMethodNameField;
        
        /// <remarks/>
        public int paymentMethodID {
            get {
                return this.paymentMethodIDField;
            }
            set {
                this.paymentMethodIDField = value;
            }
        }
        
        /// <remarks/>
        public string paymentMethodName {
            get {
                return this.paymentMethodNameField;
            }
            set {
                this.paymentMethodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class Discount {
        
        private double amountField;
        
        private string descriptionField;
        
        private double discountAmountField;
        
        private double discountPercentField;
        
        private int promotionIDField;
        
        private int promotionTypeField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double discountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        public double discountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        public int promotionID {
            get {
                return this.promotionIDField;
            }
            set {
                this.promotionIDField = value;
            }
        }
        
        /// <remarks/>
        public int promotionType {
            get {
                return this.promotionTypeField;
            }
            set {
                this.promotionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.smartRestaurant.net")]
    public partial class PromotionCard {
        
        private int promotionIDField;
        
        private string descriptionField;
        
        private double amountField;
        
        /// <remarks/>
        public int promotionID {
            get {
                return this.promotionIDField;
            }
            set {
                this.promotionIDField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPaymentMethodsCompletedEventHandler(object sender, GetPaymentMethodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentMethodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentMethodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentMethod[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentMethod[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCouponsCompletedEventHandler(object sender, GetCouponsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCouponsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCouponsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PromotionCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PromotionCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGiftVouchersCompletedEventHandler(object sender, GetGiftVouchersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGiftVouchersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGiftVouchersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PromotionCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PromotionCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDiscountsCompletedEventHandler(object sender, GetDiscountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDiscountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDiscountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Discount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Discount[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591